JetBrains/JetBrainsRuntime

src/hotspot/share/gc/g1/g1CollectedHeap.cpp
src/hotspot/share/gc/g1/g1CollectedHeap.hpp
src/hotspot/share/prims/jvmtiEnhancedRedefineClasses.cpp
src/hotspot/share/prims/jvmtiEnhancedRedefineClasses.hpp

G1 Heap does not have parallel iterate method, that is usefull in dcevm
iterate phase. According performance tests the parallel iteration is up
~25% faster then serial iteration, ratio depends on the size of heap.
Dcevm's timers did not make sense. Now, there are timers fo prologue,
doit, gc itarate and full gc phases. Iterate+fullgc time make up most
the total doit time.

G1 Heap parallel iterate method "object_par_iterate" + dcevm timers

---

src/java.base/share/classes/java/nio/file/Files.java
src/java.base/share/classes/sun/nio/ch/ChannelInputStream.java
src/java.base/windows/classes/sun/nio/fs/WindowsFileSystemProvider.java
test/jdk/java/nio/file/Files/Misc.java

Fixes InputStream.skip for nio. Fix for Files.isHidden was backport to prevent small conflict with "InputSteam.skip" patch.
tests `make run-test TEST=test/jdk/java/nio/file/Files` are ok (run under Linux through)

backport a fix required for https://youtrack.jetbrains.com/issue/RUBY-26838

---

src/java.base/windows/classes/sun/nio/fs/WindowsNativeDispatcher.java

... for a reason other that ERROR_INVALID_PARAMETER.

Follow-up to 8221852: reporting actual error when unprivileged symlink creation fails

---

src/hotspot/share/runtime/arguments.cpp
src/hotspot/share/runtime/arguments.hpp
src/hotspot/share/runtime/globals.hpp
src/hotspot/share/runtime/thread.cpp
test/hotspot/jtreg/runtime/CommandLine/ConfigFileWarning.java
test/hotspot/jtreg/runtime/CommandLine/TestLongUnrecognizedVMOption.java
test/hotspot/jtreg/runtime/CommandLine/TestNullTerminatedFlags.java
test/hotspot/jtreg/runtime/CommandLine/UnrecognizedVMOptionsProperty.java
test/hotspot/jtreg/runtime/CommandLine/VMOptionWarning.java
test/hotspot/jtreg/runtime/CommandLine/VMOptionsFile/TestVMOptionsFile.java

This patch:
1.  Change default behavior to ignore unrecognized options (+IgnoreUnrecognizedVMOptions)
2. Store all ignored values to: "java.vm.unrecognized.options" as "+BogusOption01 +BogusOption02" (space separated), see testcase
3. Explicitly set -IgnoreUnrecognizedVMOptions for couple of tests, that rely on default behavior
PS: Default separator for multiple values in property provided by os::path_separator() function, this behavior changed by second commit. The separator hard coded to " " (space)

Jbr dev vmops

---

src/java.desktop/macosx/classes/sun/lwawt/macosx/CPlatformWindow.java
src/java.desktop/macosx/native/libawt_lwawt/awt/AWTWindow.h
src/java.desktop/macosx/native/libawt_lwawt/awt/AWTWindow.m
test/jdk/jb/java/awt/Window/MacNativeTransparentTitlebarWithCustomHeight.java

Hi! 
In Fleet, we have a custom-painted title bar on macOS with non-default height. We had this logic implemented in Skiko, but recently we needed to add additional hit tests, so double click on buttons doesn't maximize the window. And we decided to move that to JBR to be consistent with our custom title bar implementation on Windows, which also uses JBR custom decorations and hit tests.

macOS: add methods to setup transparent titlebar with custom height

---

src/hotspot/share/prims/resolvedMethodTable.cpp

adjust_metod_entries_dcevm incorrectly changed the hashes of resolved
method oops stored in ResolvedMethodTable. Now all oops of old methods
are first removed, then updated and then added to table again

JBR-4312 - fix crash call ResolvedMethodTable from ServiceThread

---

src/java.desktop/macosx/native/libawt_lwawt/awt/AWTWindow.h
src/java.desktop/macosx/native/libawt_lwawt/awt/AWTWindow.m

In the previous version of the code, we didn't correctly restore the translation of resize masks into constraints for the `titlebar` view, which mostly worked but had one edge case where it broke:
If the window already takes up the full width of the screen even before entering full-screen mode, then the constraints aren't updated correctly and there will be no window controls in the hidden title bar that appears when moving the mouse to the top of the screen.
See more details in this ticket: https://youtrack.jetbrains.com/issue/FL-11420/Exit-full-screen-buttons-disappears-in-full-screen-mode
I also merged the handlers for the transparent title bar into the existing full screen handlers - I must have missed those before.

Fix view hierarchy restoration for full-screen mode on macOS

---

src/java.desktop/macosx/classes/sun/lwawt/macosx/CPlatformWindow.java
src/java.desktop/macosx/native/libawt_lwawt/awt/AWTWindow.m

This also aligns the handling of the style mask with how the other settings are applied: It uses a client property now.
The property is now also applied directly on peer initialization so that there is no need to re-apply, and the window directly appears in the correct configuration.
The issue that previously occurred was that enabling custom window decoration through the JBR API wasn't enough to keep it reliably there. It would reset everytime we applied style bits again because the internal stored style bits didn't contain the correct configuration regarding `WINDOW_FULL_CONTENT`, `WINDOW_TITLE_VISIBLE`, and `WINDOW_TRANSPARENT_TITLE_BAR`. This lead to the behavior as seen in the recording.
With these changes, the custom window decoration is now correctly applied through a custom …

FL-11598 Fix accidental reset of window configuration on macOS

---

src/java.desktop/macosx/native/libawt_lwawt/awt/AWTView.m

in place of #245 
https://en.wikipedia.org/wiki/Services_menu
Fix macOS menu services not being able to write text back to textfield due to the mismatch of ObjectiveC method signature.
`@selector(setAccessibilitySelectedText)` never selects the desired method `- (void)setAccessibilitySelectedText:(NSString *)accessibilitySelectedText` for lack of the parameter mark (a colon).

JBR-6124 Fix macOS services writing text back to textfield

---

src/java.desktop/macosx/classes/sun/lwawt/macosx/CAccessibility.java
src/java.desktop/macosx/native/libawt_lwawt/awt/a11y/ComboBoxAccessibility.m
test/jdk/java/awt/a11y/AccessibleJComboBoxVoiceOverTest.java

* Removed `(value == nil)` check in `ComboBoxAccessibility`. With this check, the value was not reassigned on every get request of `accessibilityValue`, but only on get `accessibilitySelectedChildren`. When changing focus by Tab, only get `accessibilityValue` is called, and because `value` is already not nil, the old value was returned. 
* Even with this check removed, VoiceOver still reads the old value when moving VO cursor from and to the combo box (for example using VO+Left and VO+Right shortcuts). I couldn't find the reason why it happens, but it's possible that when working with a "combo box", VoiceOver expects that there is a text field, and listens to text update events, but in case of non-editable combo box, there is no text field.
* Changed role to …

JBR-6194 Fix VoiceOver reading old JComboBox value after changing it

---

src/java.desktop/macosx/classes/sun/lwawt/macosx/CAccessible.java
src/java.desktop/macosx/classes/sun/lwawt/macosx/CAccessibleText.java
src/java.desktop/macosx/native/libawt_lwawt/awt/a11y/NavigableTextAccessibility.m

Added a call to [UAZoomChangeFocus](https://developer.apple.com/documentation/applicationservices/1458830-uazoomchangefocus?changes=_3&language=objc) function when a text component fires an `ACCESSIBLE_CARET_PROPERTY` changed event. `InputMethodRequests.getTextLocation` is used to get the caret location.
How it works in IDEA and SwingSet (video quality is not great due to GitHub limits):
https://github.com/JetBrains/JetBrainsRuntime/assets/102954094/4590f056-9b00-4b7f-b735-1de51ee9c6f6
https://github.com/JetBrains/JetBrainsRuntime/assets/102954094/4670baab-ae63-4f80-967d-e6dd9ab4426c
* There are a few cases when zoom doesn't follow caret in the Editor component in IntelliJ: when deleting text, pasting text, adding/removing tab indentation, using page up/down keys, and there may be more. …

JBR-4479 Add text caret tracking for macOS Accessibility Zoom

---

src/java.desktop/unix/classes/sun/awt/wl/WLComponentPeer.java
src/java.desktop/unix/classes/sun/awt/wl/WLToolkit.java
src/java.desktop/unix/classes/sun/awt/wl/WLWindowPeer.java

Allow to associate the application's window with .desktop file with icon and other info with -Dawt.app.id=... (DBus application name similar to WM_CLASS in X

JBR-6547 WLToolkit: no app icon in GNOME

---

test/jdk/TEST.groups

[JBR-6468](https://youtrack.jetbrains.com/issue/JBR-6468) Wayland: java/awt/datatransfer/MimeFormatsTest.java fails by timeout
Excluded the test from `jdk_awt_wayland` because it relies on `clipboard.setContents()`, which is not guaranteed to succeed in a Wayland environment unless there was some recent user input. See for example [wl_data_device:set_selection](https://wayland.app/protocols/wayland#wl_data_device:request:set_selection) that requires a "serial number of the event that triggered this request".

JBR-6468 Wayland: java/awt/datatransfer/MimeFormatsTest.java fails by timeout

---

src/hotspot/share/classfile/javaClasses.cpp
src/hotspot/share/classfile/javaClasses.inline.hpp
src/hotspot/share/memory/universe.cpp
src/hotspot/share/memory/universe.hpp
src/hotspot/share/prims/jvmtiEnhancedRedefineClasses.cpp
src/hotspot/share/prims/jvmtiEnhancedRedefineClasses.hpp

Move flag is_inside_redefinition to Universe:: to fix macos-aarch64 build, same problem as in jbr17, that is already fixed & merged.

JBR-6419 - fix macos-aarch64 build problem

---

src/java.desktop/unix/classes/sun/awt/wl/WLSMGraphicsConfig.java
src/java.desktop/unix/classes/sun/java2d/wl/WLSMSurfaceData.java

[JBR-6469](https://youtrack.jetbrains.com/issue/JBR-6469) Wayland: java/awt/image/ColorModel/DrawCustomColorModel.java throws UnsupportedOperationException
When surface's type is `SurfaceType.IntArgb`, an unusual blitting loop called `OpaqueCopyArgbToAny` is used to draw an image onto Frame's graphics. That loop requires the target surface to provide its raster, which no platform surfaces really implement and `WLSMSurfaceData.getRaster()` throws UOE.
With an experiment I proved that at least the GNOME Shell implementation of the Wayland server expects memory buffer to have their alpha pre-multiplied, so the correct surface type should be `SurfaceType.IntArgbPre` anyway and that avoids that loop and makes the test pass. I also corrected the color model to indicate that the color components …

JBR-6469 Wayland: java/awt/image/ColorModel/DrawCustomColorModel.java throws UnsupportedOperationException

---

src/java.desktop/unix/native/common/java2d/wl/WLBuffers.c
src/java.desktop/unix/native/libawt_wlawt/WLComponentPeer.c

When the size of the buffer changes, cancel the frame callback and make sure that the next surface commit happens with the new buffer.

JBR-6598 Wayland: window gets un-maximized after switching

---

src/java.desktop/unix/classes/sun/awt/wl/WLComponentPeer.java
src/java.desktop/unix/classes/sun/awt/wl/WLGraphicsEnvironment.java
src/java.desktop/unix/native/common/java2d/wl/WLBuffers.c
src/java.desktop/unix/native/common/java2d/wl/WLSMSurfaceData.c

Artificially constrain the maximum size of the peer based on the available screen space; Wayland doesn't provide any hints or restrictions for the buffer size.
On the native side, throw OOME early as creating very large buffers may freeze the entire operating system like it happens with XWayland on my machine.
[JBR-6617](https://youtrack.jetbrains.com/issue/JBR-6617) Wayland: java/awt/Frame/HugeFrame/HugeFrame.java crashes JVM

JBR-6617 Wayland: java/awt/Frame/HugeFrame/HugeFrame.java crashes JVM

---

src/java.desktop/macosx/native/libawt_lwawt/java2d/metal/MTLRenderQueue.m

Performing flush of pending rendering operation before destroying MTLGraphicsConfig

JBR-6522 macOS: SIGSEGV at [libawt_lwawt.dylib+0x8eaa8] MTLGC_DestroyMTLGraphicsConfig

---

src/java.desktop/macosx/classes/sun/lwawt/macosx/CAccessibility.java

`CAccessibility.invokeAndWait` can return null if no default value is specified, so in this case we'll get  `java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "sun.lwawt.macosx.CAccessibility.invokeAndWait(java.util.concurrent.Callable, java.awt.Component)" is null`. 
With the `false` default value `invokeAndWait` will never return null.

JBR-6472 Add default value in CAccessibility.isComboBoxEditable to avoid NPE

---

src/hotspot/share/interpreter/linkResolver.cpp

Kotlin compiler can create a new static variable `INSTANCE` on redefinition, that is normally initialized by `<clinit>`, but in case of redefinition the initializer is not called, since instances of static variables from old class must be preserved and initizelizer for a new class shoudl initialize only new variables. So it is not work for JVM level dcevm, but for high level agent. HotswapAgent solves the problem creating static method `$$ha$clinit`, that serves for initialization of new static varables.

JBR-6647 Disable check for final field access from method $$ha$clinit

---

src/java.desktop/unix/classes/sun/awt/wl/WLComponentPeer.java

OOME was the result of trying to allocate a buffer of 0 size. This should never happen under normal circumstances.

JBR-6722 OutOfMemoryError: Failed to allocate Wayland surface buffer

---

test/jdk/jb/build/CDSArchivesTest.sh

The previous version of the test works well only when the test was launched from Terminal. When it was launched via jtreg it could not correctly read the variable IMPLEMENTOR_VERSION using source on Linux.
The test was rewritten to read the value for this variable in another way - via grep.

fixup! JBR-6246 add default CDS archives into jbrsdk distributions

---

src/hotspot/share/gc/g1/g1CollectedHeap.cpp
src/hotspot/share/gc/g1/g1CollectedHeap.hpp
src/hotspot/share/prims/jvmtiEnhancedRedefineClasses.cpp

This patch addresses unsynchronized parallel access to ChangePointersObjectClosure._tmp_obj by creating a separate instance for each thread, enhancing thread safety. Additionally, it deems parallel DCEVM iteration in G1 as redundant and removes it.

JBR-6674 Fix parallel oops iteration in dcevm redefinition

---

src/java.desktop/share/classes/sun/swing/AccessibleAnnouncer.java
src/java.desktop/windows/native/libawt/windows/AccessibleAnnouncer/JawsAnnouncer.cpp

* Execute `AccessibleAnnouncer.nativeAnnounce` on a background thread on Windows to fix UI freezes. IntelliJ calls this method from EDT, but it doesn't need to run on EDT because on Windows it simply calls screen readers API without interacting with UI components. Additionally, when using a background thread, the JAWS `SayString` method, which previously could have been running for multiple seconds, is now executed immediately as expected, but the root cause of previous delays is unclear.
* In `JawsAnnouncer`, initialize COM library with the multithreaded model to allow executing it from different threads. By making `comInitializer` non-static, now COM is initialized and uninitialized on every call of the method as required by the …

JBR-6593 Fix UI freezes with JAWS announcements

---

src/java.desktop/share/classes/sun/swing/AccessibleAnnouncer.java

Follow-up on #272. Set unique name for the AccessibleAnnouncer thread for easier debugging.

JBR-6593 Set unique name for the AccessibleAnnouncer thread

---

src/java.desktop/unix/classes/sun/awt/wl/WLComponentPeer.java

Added check for unavailable cursor pData

JBR-6787 WLToolkit/wsl: crash in WLComponentPeer.setCursor

---

src/java.desktop/unix/classes/sun/awt/wl/WLComponentPeer.java
src/java.desktop/unix/native/libawt_wlawt/WLComponentPeer.c

Certain Wayland compositors (wlroots) invalidate xdg_surface after window with popup loses focus. Subsequent attempts to commit the popup window fail with protocol error
"xdg_surface has never been configured".
Handle popup_done event by hiding the popup window and emitting WINDOW_CLOSING Window event.

JBR-6763 Wayland: handle popup_done event

---

src/hotspot/share/prims/jvmtiExport.hpp
src/hotspot/share/prims/jvmtiRedefineClasses.cpp
src/hotspot/share/runtime/globals.hpp
src/hotspot/share/runtime/init.cpp

[JBR-6826](https://youtrack.jetbrains.com/issue/JBR-6826) Include JDK-8324241 in the JBR17/21 builds
The original pull request: https://github.com/openjdk/jdk/pull/17509
The original issue: https://bugs.openjdk.org/browse/JDK-8324241
8324241: Always record evol_method deps to avoid excessive method flushing
Reviewed-by: eastigeevich, phh, coleenp, dlong, shade
This commit passes tier1 tests.

JBR-6826 Include JDK-8324241 in the JBR17/21 builds

---

src/java.desktop/unix/native/common/java2d/wl/WLSMSurfaceData.c

[JBR-6884](https://youtrack.jetbrains.com/issue/JBR-6884) SIGSEGV in Java_sun_java2d_wl_WLSMSurfaceData_pixelsAt

JBR-6884 SIGSEGV in Java_sun_java2d_wl_WLSMSurfaceData_pixelsAt

---

src/java.desktop/unix/classes/sun/awt/wl/WLDecoratedPeer.java
src/java.desktop/unix/classes/sun/awt/wl/WLDialogPeer.java
src/java.desktop/unix/classes/sun/awt/wl/WLFrameDecoration.java
src/java.desktop/unix/classes/sun/awt/wl/WLFramePeer.java

[JBR-6895](https://youtrack.jetbrains.com/issue/JBR-6895) Wayland: cursor changes to resize at edges even when window is maximized

JBR-6895 Wayland: cursor changes to resize at edges even when window is maximized

---

jb/project/tools/common/scripts/common.sh
jb/project/tools/linux/scripts/mkimages_aarch64.sh
jb/project/tools/linux/scripts/mkimages_x64.sh
jb/project/tools/linux/scripts/mkimages_x86.sh
jb/project/tools/mac/scripts/mkimages.sh
jb/project/tools/windows/scripts/mkimages_aarch64.sh
jb/project/tools/windows/scripts/mkimages_x64.sh
jb/project/tools/windows/scripts/mkimages_x86.sh

The option `-w` was introduced into mkimages scripts. The option add the parameter `--disable-warnings-as-errors` into `configure`.
Note: `configure` is not invoked when mkimages scripts are started with the option `-i`

JBR-6915 add the option -w into mkimages scripts

---

src/java.desktop/macosx/native/libawt_lwawt/java2d/metal/MTLPipelineStatesStorage.m

Corrected invalid usage of dealloc method, fixed memory leaks.

JBR-6911 IDE crashes (EXC_BAD_ACCESS) after disconnecting the secondary display if a markdown file is opened (macOS Sonoma 14.4.1)

---

src/java.desktop/unix/classes/sun/java2d/wl/WLVolatileSurfaceManager.java

[JBR-6926](https://youtrack.jetbrains.com/issue/JBR-6926) Wayland: fonts are aliased/grainy on first start
The fix is to update volatile images created for offscreen painting of a `Component` whenever that component appears on a monitor with a different scale.

JBR-6926 Wayland: fonts are aliased/grainy on first start

---

src/java.desktop/unix/native/common/java2d/wl/WLBuffers.c
src/java.desktop/unix/native/libawt_wlawt/WLCursor.c
src/java.desktop/unix/native/libawt_wlawt/WLRobotPeer.c
src/java.desktop/unix/native/libawt_wlawt/WLToolkit.c
src/java.desktop/unix/native/libawt_wlawt/WLToolkit.h

[JBR-7010](https://youtrack.jetbrains.com/issue/JBR-7010) Wayland: Swing window resizing is not smooth enough
By re-using memory buffers and allocating them lazily this commit boosts FPS during interactive resize by ~3x.

JBR-7010 Wayland: Swing window resizing is not smooth enough

---

src/java.desktop/macosx/native/libawt_lwawt/java2d/metal/MTLGlyphCache.m
src/java.desktop/macosx/native/libawt_lwawt/java2d/metal/MTLTextRenderer.m

1. As we started committing the command buffer on glyph cache flush, this invalidates the current encoder. We need to `MTLTR_ValidateGlyphCache` after the flush, not before.
2. There's no reason to maintain separate glyph cache invalidation logic for this singe case (which is a no-op in reality), so just free the cache instead.

JBR-7020 Reorder LCD glyph cache freeing and validation

---

src/java.desktop/unix/classes/sun/awt/X11/XToolkit.java

[JBR-5611](https://youtrack.jetbrains.com/issue/JBR-5611) Window header is visible but body not on Linux Ubuntu with external display
In general, we cannot estimate insets when there's more than one monitor except for the "first" monitor, the one at the top left of the whole setup.
Consider a two-screen setup where screens are on top of one another. The topmost screen with a status bar at the top and a dock at the bottom of the other screen that is at the bottom. One has the scale of 1.5x and the other 1.25x. So the overall height in the user space will be
`(status-bar-height + free-area-1-height)/1.5 + (free-area-2-height + dock-height)/1.25`.
`_NET_WORKAREA` gives us this value when in xinerama mode. `GraphicsConfiguration.getBounds()` gives us the individual
expressions …

JBR-5611 Window header is visible but body not on Linux Ubuntu with external display

---

src/java.desktop/unix/native/common/java2d/wl/WLBuffers.c

Clean up the damage list when resizing a surface.
Additionally, clamp the damaged area before copying to its current actual size in order to safeguard against invalid external input.

JBR-7058 Wayland: IDE hang on the popup appearance

---

src/java.desktop/share/classes/javax/swing/JTree.java
src/jdk.accessibility/windows/classes/com/sun/java/accessibility/internal/AccessBridge.java
test/jdk/javax/accessibility/8249806/AccessibleJTreeNodeAccessibleParentTest.java

This fixes an issue with `AccessibleJTreeNode#getBounds`, which adjusts the node's bounds according to the parent node:
https://github.com/JetBrains/JetBrainsRuntime/blob/ce6f4d023beef597cb670072e093eeb0fb25dfd5/src/java.desktop/share/classes/javax/swing/JTree.java#L5425-L5437
For nodes whose parent is the invisible root, `getBounds` was returning null, and it caused issues with assistive technology like macOS Accessibility Zoom.
This also matches behavior in `AccessibleJTree#getAccessibleChild` which creates accessible node for the root only if it's visible:
https://github.com/JetBrains/JetBrainsRuntime/blob/ce6f4d023beef597cb670072e093eeb0fb25dfd5/src/java.desktop/share/classes/javax/swing/JTree.java#L4541-L4575
Invisible root has an item in the hierarchy:
In IntelliJ it caused issues …

JBR-6808 Don't create AccessibleJTreeNode for the tree root if it's not visible

---

src/java.desktop/unix/classes/sun/awt/wl/WLComponentPeer.java
src/java.desktop/unix/classes/sun/awt/wl/WLWindowPeer.java
src/java.desktop/unix/classes/sun/java2d/wl/WLSMSurfaceData.java
src/java.desktop/unix/native/common/java2d/wl/WLBuffers.c
src/java.desktop/unix/native/common/java2d/wl/WLBuffers.h
src/java.desktop/unix/native/common/java2d/wl/WLSMSurfaceData.c
src/java.desktop/unix/native/libawt_wlawt/WLComponentPeer.c

[JBR-7206](https://youtrack.jetbrains.com/issue/JBR-7206) Wayland: Stylepad demo flickers when resizing on KDE
The main idea is to make sure all kinds of sizes (both of the buffer and of the surface) are set in one and only one surface commit.

JBR-7206 Wayland: Stylepad demo flickers when resizing on KDE

---

src/java.desktop/unix/classes/sun/java2d/wl/WLVolatileSurfaceManager.java

[JBR-7202](https://youtrack.jetbrains.com/issue/JBR-7202) wayland: memory leak when resizing windows
Instead of relying on the property change event, it is enough to signal `IMAGE_INCOMPATIBLE` when this surface manager gets validated against a graphics configuration with a different transform. This will result in "invalid" buffers dropped by the component's repaint manager and new buffers created with no references that prevent garbage collection.

JBR-7202 wayland: memory leak when resizing windows

---

src/java.desktop/unix/classes/sun/awt/wl/WLDisplay.java
src/java.desktop/unix/classes/sun/awt/wl/WLToolkit.java
src/java.desktop/unix/native/libawt_wlawt/WLToolkit.c

[JBR-7237](https://youtrack.jetbrains.com/issue/JBR-7237) Fix circular dependency of Wayland and Vulkan initialization

JBR-7237 Separate display connect from WLToolkit initialization

---

src/hotspot/share/prims/jvmtiEnv.cpp

If an application is paused at a breakpoint in method M of class C and method M is modified N times, each modification triggers N redefinitions of class C. This patch fixes this bug.

JBR-7245 DCEVM: Fix multiple class modification at breakpoint

---

src/java.desktop/share/glsl/vulkan/color.vert
src/java.desktop/share/native/common/java2d/vulkan/VKRenderQueue.c
src/java.desktop/share/native/common/java2d/vulkan/VKRenderer.c
src/java.desktop/share/native/common/java2d/vulkan/VKRenderer.h
src/java.desktop/share/native/common/java2d/vulkan/VKVertex.c
src/java.desktop/share/native/common/java2d/vulkan/VKVertex.h

Implemented FILL_PARALLELOGRAM RQ primitive
Changed color shader to use push constant for color

JBR-7256 Vulkan: Implement FILL_PARALLELOGRAM primitive for flat color rendering

---

src/java.desktop/unix/classes/sun/awt/wl/WLComponentPeer.java
test/jdk/jb/java/awt/Focus/ContextMenuFocusTest.java

[JBR-7072](https://youtrack.jetbrains.com/issue/JBR-7072) Wayland: clicks on items of floating context menus are ignored
The origin of the problem lies in an unexpected sequence of FocusEvent's generated on the popup invocation. In order to make that sequence more standard, I used the corresponding method from LWComponentPeer as a template. It doesn't cover all Wayland cases yet and falls through to `WLKeyboardFocusManagerPeer.SNFH_FAILURE` case in some instances, but that's a task for another day.
Also verified that this fix did not regress on the test from [JBR-6145](https://youtrack.jetbrains.com/issue/JBR-6145) [Wayland toolkit] Popup windows aren't focusable.

JBR-7072 Wayland: clicks on items of floating context menus are ignored

---

src/java.desktop/share/classes/sun/java2d/vulkan/VKInstance.java
src/java.desktop/share/native/common/java2d/vulkan/VKBase.c
src/java.desktop/share/native/common/java2d/vulkan/VKBase.h
src/java.desktop/unix/classes/sun/awt/wl/WLGraphicsDevice.java
src/java.desktop/unix/classes/sun/awt/wl/WLGraphicsEnvironment.java
src/java.desktop/unix/classes/sun/awt/wl/WLToolkit.java
src/java.desktop/unix/native/common/java2d/vulkan/WLVKSurfaceData.c
src/java.desktop/unix/native/libawt_wlawt/WLGraphicsEnvironment.c

This adds asynchronous Vulkan initialization.
1. `WLGraphicsEnvironment` starts Vulkan initialization in separate thread and proceeds with Wayland initialization
2. Before `vkGetPhysicalDeviceWaylandPresentationSupportKHR` Vulkan init waits for the `wl_display` to become available
3. `VKInstance.isVulkanEnabled()` which is used later by `WLGraphicsDevice` waits for the Vulkan initialization to finish

JBR-7237 Fix cyclic dependency of Wayland and Vulkan initialization

---

src/java.desktop/share/native/common/java2d/vulkan/VKRenderQueue.c
src/java.desktop/share/native/common/java2d/vulkan/VKRenderer.c
src/java.desktop/share/native/common/java2d/vulkan/VKRenderer.h

Implemented flat color shape rendering

JBR-7305 Vulkan: Implement FILL_SPANS primitive for flat color rendering

---

src/java.desktop/unix/classes/sun/awt/wl/WLClipboard.java
src/java.desktop/unix/classes/sun/awt/wl/WLDataTransferer.java

[JBR-7254](https://youtrack.jetbrains.com/issue/JBR-7254) Impossible to copy/paste files in Project tree

JBR-7254 Impossible to copy/paste files in Project tree

---

src/java.desktop/unix/classes/sun/awt/wl/WLComponentPeer.java
test/jdk/jb/javax/swing/Popup/WLPopupResize.java

[JBR-7259](https://youtrack.jetbrains.com/issue/JBR-7259) Find Usages popup can't be resized under Wayland
Popup's positioner size has to be in sync with popup's buffer size.

JBR-7259 Find Usages popup can't be resized under Wayland

---

src/java.base/share/classes/java/util/zip/ZipFile.java
test/hotspot/jtreg/serviceability/jvmti/RedefineClasses/RedefineSharedClass.java
test/jdk/java/nio/Buffer/LimitDirectMemory.java
test/jdk/java/util/zip/TestZipError.java

See https://youtrack.jetbrains.com/issue/JBR-7392/Allow-using-NIO-in-ZipFile for discussion.
Tests against upstream JDK: https://github.com/knisht/jdk/pull/1
Tests with enabled property: https://github.com/knisht/jdk/pull/2. It contains an additional failure of `RedefineSharedClass`, which is fixable.

JBR-7392: Use NIO FS in ZipFile

---

src/hotspot/share/classfile/classFileParser.cpp
src/hotspot/share/classfile/defaultMethods.cpp
src/hotspot/share/oops/instanceKlass.cpp
src/hotspot/share/prims/jvmtiClassFileReconstituter.cpp
src/hotspot/share/prims/jvmtiManageCapabilities.cpp

We experience a crash when attaching async-profiler to a running JVM in combination with the `AllowEnhancedClassRedefinition` flag. Debugging showed that this is caused by https://github.com/JetBrains/JetBrainsRuntime/blob/41109ce8ba5e7ca202739ea4c03c9c4d7ce2dcff/src/hotspot/share/prims/jvmtiEnv.cpp#L2985 because `JvmtiExport::can_maintain_original_method_order()` is true but the method ordering array wasn't initialized.
We don't quite understand why the flag unconditionally overrides the capability, as the method ordering array is set when the instance class is parsed initially. Retroactively changing the capability does not re-initialize the existing classes, leading to a state mismatch and a JVM crash. Therefore, we propose removing this override.
Alternatively, the …

[JVM Crash] Remove AllowEnhancedClassRedefinition capability override

---

src/java.desktop/share/native/common/java2d/vulkan/VKBase.c
src/java.desktop/share/native/common/java2d/vulkan/VKBase.h
src/java.desktop/share/native/common/java2d/vulkan/VKRenderer.c
src/java.desktop/share/native/common/java2d/vulkan/VKRenderer.h
src/java.desktop/share/native/common/java2d/vulkan/VKSurfaceData.c

Moved shared VkRenderPass to the logical device

JBR-7452 Vulkan: Reuse VkRenderPass for multiple renderers

---

src/hotspot/share/prims/jvmtiEnhancedRedefineClasses.cpp
src/hotspot/share/prims/jvmtiEnhancedRedefineClasses.hpp

caused by JBR-7219 ("Rebasing JBR21 on top of OpenJDK 21.0.4") and changes in G1 nmethods unregister

JBR-7447 use new method for unregister nmethods in G1

---

src/java.base/share/classes/java/util/zip/ZipFile.java

[JBR-7466](https://youtrack.jetbrains.com/issue/JBR-7466) Exception on VM startup with `-Djava.util.zip.use.nio.for.zip.file.access=true`
Follow-up for #413 : I encountered an exception during VM startup https://youtrack.jetbrains.com/issue/JBR-7392/Allow-using-NIO-in-ZipFile#focus=Comments-27-10185488.0-0 .

JBR-7466 Exception on VM startup with `-Djava.util.zip.use.nio.for.zip.file.access=true`

---

src/java.desktop/unix/native/libawt_wlawt/WLToolkit.c

[JBR-7397](https://youtrack.jetbrains.com/issue/JBR-7397) CLion 2024.2-EAP/Wayland crashes on startup with Miriway
Check if all non-optional interfaces are supported before actually starting to run

JBR-7397 CLion 2024.2-EAP/Wayland crashes on startup with Miriway

---

src/java.desktop/unix/classes/sun/awt/wl/WLComponentPeer.java
src/java.desktop/unix/classes/sun/awt/wl/WLDecoratedPeer.java
src/java.desktop/unix/classes/sun/awt/wl/WLFramePeer.java
src/java.desktop/unix/classes/sun/awt/wl/WLGraphicsConfig.java
src/java.desktop/unix/classes/sun/awt/wl/WLGraphicsDevice.java
src/java.desktop/unix/classes/sun/java2d/vulkan/WLVKSurfaceData.java

[JBR-7313](https://youtrack.jetbrains.com/issue/JBR-7313) Wayland: error: xdg_surface buffer does not match the configured maximized state
The most important part is to keep the surface size that came from the Wayland server in the 'configure' event and pass it to `nativeSetSurfaceSize()` and `nativeSetWindowGeometry()` unmodified, especially when in maximized state.
It seems that passing the scale to `SurfaceData` is unnecessary as it is not used in `WLSMSurfaceData`. If it is safe to remove the scale from `WLVKSurfaceData`, let's do that and free SurfaceData from worrying about scaling altogether.

JBR-7313 Wayland: error: xdg_surface buffer does not match the configured maximized state

---

src/java.desktop/unix/native/common/java2d/wl/WLBuffers.c
test/jdk/jb/java/awt/Window/Reshow.java

[JBR-7516](https://youtrack.jetbrains.com/issue/JBR-7516) Wayland: DamageList_AddList: Assertion `list != add' failed
The main problem was that both `list` and `add` were `NULL` at the time of the check. This is normal and the check was corrected to account for such a possibility.
However, since buffers can be re-used for a different surface of the same `java.awt.Window` (which will likely have the same size after the second `setVisible(true)`), it's important that those buffers do not retain any residual information from their previous "life".

JBR-7516 Wayland: DamageList_AddList: Assertion `list != add' failed

---

src/java.desktop/unix/classes/sun/awt/wl/WLComponentPeer.java
src/java.desktop/unix/classes/sun/awt/wl/WLFramePeer.java
test/jdk/jb/java/awt/Window/ShowMaximized.java

[JBR-7493](https://youtrack.jetbrains.com/issue/JBR-7493) Wayland: can't start in maximized state on WSL
Two distinct problems were fixed:
* `assignSurface()` was called too early before the real (coming from the `configure` event) size of the surface had been specified
* it should not be possible to change the size of a maximized surface, except when the change is initiated by Wayland itself (when, for example, the screen scale changes)

JBR-7493 Wayland: can't start in maximized state on WSL

---

src/java.desktop/macosx/classes/sun/lwawt/macosx/CAccessibleText.java
src/java.desktop/macosx/native/libawt_lwawt/awt/a11y/NavigableTextAccessibility.m

* This method allows for third-party tools to modify text component contents through the accessibility API on macOS;
* In the legacy JavaTextAccessibility.m, there were methods `accessibilityIsValueAttributeSettable` and `accessibilitySetValueAttribute`, but in the current implementation we need to implement `setAccessibilityValue` and `isAccessibilitySelectorAllowed`;
* The `setAccessibilityValue` method is implemented similarly to `NavigableTextAccessibility.setAccessibilitySelectedText`. On the Java side, it calls `AccessibleEditableText.setTextContents` according to the comment in `JavaTextAccessibility.accessibilitySetValueAttribute`;
* The `isAccessibilitySelectorAllowed` method is implemented similarly to `JavaTextAccessibility.accessibilityIsValueAttributeSettable`: it checks if …

JBR-8216 Implement setAccessibilityValue method for NavigableTextAccessibility

---

src/java.desktop/windows/native/libawt/windows/jbr_CustomTitleBarControls.cpp

We had an issue reported on Jewel that the custom titlebar/decorated window did not support RTL alignment (https://github.com/JetBrains/intellij-community/pull/3087).
The initial solution involved hiding the controls and drawing them manually on the correct side. But as this is an issue with the title bar, we thought it would be better to fix inside the runtime.
While debugging the JBR, I found three possible solutions:
The first solution was simply usin the `WS_EX_LAYOUTRTL` and `WS_EX_RTLREADING` on the client side. However, the button orders did not match the expectations and hover/clicks were all bugged out. ([video](https://github.com/JetBrains/intellij-community/pull/3087#issuecomment-2958845896))
Even though this is a simple solution, it would still require the client app (or the …

Adding support for RTL Custom TitleBar
