JetBrains/JetBrainsRuntime

- src/java.base/share/classes/sun/net/www/protocol/http/BasicAuthentication.java
- src/java.base/share/classes/sun/net/www/protocol/http/HttpURLConnection.java
- src/java.net.http/share/classes/jdk/internal/net/http/AuthenticationFilter.java
- src/java.net.http/share/classes/jdk/internal/net/http/ConnectionPool.java
- src/java.net.http/share/classes/jdk/internal/net/http/Http1Response.java
- src/java.net.http/share/classes/jdk/internal/net/http/HttpRequestImpl.java
- src/java.net.http/share/classes/jdk/internal/net/http/HttpResponseImpl.java
- src/java.net.http/share/classes/jdk/internal/net/http/MultiExchange.java
- src/java.net.http/share/classes/jdk/internal/net/http/RawChannelTube.java
- src/java.net.http/share/classes/jdk/internal/net/http/common/Log.java
- src/java.net.http/share/classes/jdk/internal/net/http/common/Utils.java
- src/java.net.http/share/classes/jdk/internal/net/http/websocket/OpeningHandshake.java
- src/java.net.http/share/classes/jdk/internal/net/http/websocket/RawChannel.java
- src/jdk.httpserver/share/classes/com/sun/net/httpserver/BasicAuthenticator.java
- test/jdk/com/sun/net/httpserver/bugs/8199849/BasicAuthenticatorCharset.java
- test/jdk/com/sun/net/httpserver/bugs/8199849/ParamTest.java
- test/jdk/com/sun/net/httpserver/bugs/8199849/TestHttpUnicode.java
- test/jdk/java/net/httpclient/AuthFilterCacheTest.java
- test/jdk/java/net/httpclient/AuthSchemesTest.java
- test/jdk/java/net/httpclient/ProxyServer.java
- test/jdk/java/net/httpclient/websocket/DummySecureWebSocketServer.java
- test/jdk/java/net/httpclient/websocket/DummyWebSocketServer.java
- test/jdk/java/net/httpclient/websocket/SecureSupport.java
- test/jdk/java/net/httpclient/websocket/Support.java
- test/jdk/java/net/httpclient/websocket/WSHandshakeExceptionTest.java
- test/jdk/java/net/httpclient/websocket/WebSocketProxyTest.java
- test/jdk/java/net/httpclient/websocket/WebSocketTest.java
See https://youtrack.jetbrains.com/issue/JBR-2620
Tests `make run-test TEST=test/jdk/java/net/httpclient` are ok on Linux
> Backport websockets over proxy fixes

- src/hotspot/share/runtime/thread.cpp
- src/hotspot/share/runtime/thread.hpp
- src/hotspot/share/services/management.cpp
CompilationMXBean#getTotalCompilationTime precise implementation (discreteness fix).
> JBR-2577 implemented precise CompilationMXBean#getTotalCompilationTime

- src/hotspot/share/runtime/globals.hpp
AllowEnhancedClassRedefinition is disabled now, must be turned on using -XX:+AllowEnhancedClassRedefinition
> AllowEnhancedClassRedefinition is false (disabled) by default

- src/java.desktop/macosx/native/libawt_lwawt/awt/AWTWindow.m
Regression was due to incorrect merge in pull/73.
Failed test:
jb/java/awt/event/MouseEvent/MouseMoveEventFallThroughTest.java
> fix regression after PR 73

- jb/project/tools/common/scripts/common.sh
- jb/project/tools/common/static_conf_args.txt
- jb/project/tools/linux/scripts/mkimages_aarch64.sh
- jb/project/tools/linux/scripts/mkimages_x64.sh
- jb/project/tools/linux/scripts/mkimages_x86.sh
- jb/project/tools/mac/scripts/mkimages.sh
- jb/project/tools/windows/scripts/mkimages_x64.sh
- jb/project/tools/windows/scripts/mkimages_x86.sh
Pending positive tests results
> JBR-4452: Update crash report message with JBR youtrack link instead of bugreport.java.com

- src/java.desktop/macosx/classes/sun/lwawt/macosx/CPlatformWindow.java
- src/java.desktop/macosx/native/libawt_lwawt/awt/AWTWindow.m
- test/jdk/jb/java/awt/Window/MacNativeSetRoundedCorners.java
[JBR-4563](https://youtrack.jetbrains.com/issue/JBR-4563) Rounded corners for native Window on Mac OS
> JBR-4563 Rounded corners for native Window on Mac OS

- src/java.desktop/windows/classes/sun/awt/windows/WWindowPeer.java
- src/java.desktop/windows/native/libawt/windows/awt_Window.cpp
I did fix `undeclared identifier: DWMWA_BORDER_COLOR`
> JBR-5139 Support color for rounded borders on Windows (version 2)

- src/jetbrains.api/version.properties
Fix incremental compilation bug in #210
> JBR-5213  JBR API v1.5.0 - fix API hash

- src/hotspot/share/gc/shared/dcevmSharedGC.cpp
- src/hotspot/share/prims/jvmtiEnhancedRedefineClasses.cpp
- src/hotspot/share/utilities/vmError.cpp
> JBR-6643 - fix GitHub actions builds

- src/hotspot/share/prims/jvmtiEnhancedRedefineClasses.cpp
Please check ZERO build in GH actions
https://github.com/JetBrains/JetBrainsRuntime/actions/runs/7788698085
> JBR-6643 - additional fix for GitHub actions ZERO build

- src/java.desktop/unix/classes/sun/awt/wl/WLGraphicsDevice.java
[JBR-6467](https://youtrack.jetbrains.com/issue/JBR-6467) Wayland: java/awt/GraphicsConfiguration/NormalizingTransformTest/NormalizingTransformTest.java fails
> JBR-6467 Wayland: java/awt/GraphicsConfiguration/NormalizingTransformTest/NormalizingTransformTest.java fails

- src/jdk.attach/aix/classes/sun/tools/attach/VirtualMachineImpl.java
- src/jdk.attach/linux/classes/sun/tools/attach/VirtualMachineImpl.java
- src/jdk.attach/share/classes/sun/tools/attach/HotSpotVirtualMachine.java
the fix is still needed in modern jbrs
> JBR-1061 .attach_pid files in the working dir

- src/java.desktop/unix/native/libawt_wlawt/WLCursor.c
[JBR-6519](https://youtrack.jetbrains.com/issue/JBR-6519) Linux: SIGSEGV at [libwayland] wl_proxy_get_version
Guard against passing NULL to libwayland
> JBR-6519 Linux: SIGSEGV at [libwayland] wl_proxy_get_version

- src/java.desktop/macosx/native/libawt_lwawt/java2d/metal/MTLGraphicsConfig.m
Fix of MT access to shared data in MTLGraphicsConfigInfo
> JBR-6522 macOS: SIGSEGV at [libawt_lwawt.dylib+0x8eaa8] MTLGC_DestroyMTLGraphicsConfig

- src/java.desktop/unix/classes/sun/awt/wl/WLComponentPeer.java
- src/java.desktop/unix/classes/sun/awt/wl/WLRobotPeer.java
- src/java.desktop/unix/classes/sun/awt/wl/WLToolkit.java
- src/java.desktop/unix/classes/sun/java2d/wl/WLSMSurfaceData.java
- src/java.desktop/unix/native/common/java2d/wl/WLSMSurfaceData.c
[JBR-6504](https://youtrack.jetbrains.com/issue/JBR-6504) Wayland: optional Robot capability to peek at current window's pixels
> JBR-6504 Wayland: optional Robot capability to peek at current window's pixels

- src/java.desktop/unix/classes/sun/awt/wl/WLComponentPeer.java
[JBR-6783](https://youtrack.jetbrains.com/issue/JBR-6783) MouseEvent/MenuDragMouseEventAbsoluteCoordsTest/MenuDragMouseEventAbsoluteCoordsTest.java: Found one Java-level deadlock
The failing test was fixed by the `performUnlocked()` in `checkIfOnNewScreen()`. I also improved synchronization throughout the `WLComponentPeer` class.
> JBR-6783 MouseEvent/MenuDragMouseEventAbsoluteCoordsTest/MenuDragMouseEventAbsoluteCoordsTest.java: Found one Java-level deadlock

- jb/project/tools/linux/scripts/mkimages_x64.sh
Added explicit platform target
> JBR-6785 wsl: update build scripts for linux target

- README.md
> JBR-6789 jbr21/wayland: update build instructions

- src/java.desktop/unix/classes/sun/awt/wl/WLDecoratedPeer.java
- src/java.desktop/unix/classes/sun/awt/wl/WLDialogPeer.java
- src/java.desktop/unix/classes/sun/awt/wl/WLFrameDecoration.java
- src/java.desktop/unix/classes/sun/awt/wl/WLFramePeer.java
[JBR-6576](https://youtrack.jetbrains.com/issue/JBR-6576) Wayland: exception when double-clicking dialog title bar
> JBR-6576 Wayland: exception when double-clicking dialog title bar

- src/java.desktop/linux/native/libawt/awt/system_properties.c
- src/java.desktop/unix/classes/sun/awt/wl/WLFrameDecoration.java
[JBR-7209](https://youtrack.jetbrains.com/issue/JBR-7209) Wayland: modernize window decorations
See also [JBR-6376](https://youtrack.jetbrains.com/issue/JBR-6376) JBRApi to query current desktop theme
> JBR-7209 Wayland: modernize window decorations

- make/modules/java.desktop/lib/Awt2dLibraries.gmk
- src/hotspot/share/gc/z/zArray.inline.hpp
- src/hotspot/share/utilities/chunkedList.hpp
- src/hotspot/share/utilities/events.hpp
- src/hotspot/share/utilities/growableArray.hpp
- src/hotspot/share/utilities/linkedlist.hpp
- src/java.desktop/linux/native/libjsound/PLATFORM_API_LinuxOS_ALSA_MidiIn.c
- src/java.desktop/linux/native/libjsound/PLATFORM_API_LinuxOS_ALSA_MidiUtils.c
- src/java.desktop/share/native/libfontmanager/sunFont.c
Picked up fixes to support gcc 14
> JBR-7233 JBR21: Cannot build on fedora 40 without --disable-warnings-as-errors

- src/java.desktop/share/native/common/java2d/vulkan/VKBase.c
Added missing header (jni_util.h)
> JBR-7308 Vulkan: Build failure in vulkan enabled builds

- src/java.desktop/unix/classes/sun/awt/PlatformGraphicsInfo.java
[JBR-7390](https://youtrack.jetbrains.com/issue/JBR-7390) Wayland: need better headless exception message
> JBR-7390 Wayland: need better headless exception message

- src/java.desktop/share/native/common/java2d/vulkan/VKBase.h
- src/java.desktop/share/native/common/java2d/vulkan/VKRenderQueue.c
- src/java.desktop/share/native/common/java2d/vulkan/VKRenderer.c
- src/java.desktop/share/native/common/java2d/vulkan/VKRenderer.h
- src/java.desktop/share/native/common/java2d/vulkan/VKSurfaceData.c
Refactored rendering code. Provided common implementation for fill and draw operations.
> JBR-7420 Vulkan: Implement DRAW_PARALLELOGRAM primitive for flat color rendering

- src/java.desktop/unix/classes/sun/awt/wl/WLComponentPeer.java
- src/java.desktop/unix/native/libawt_wlawt/WLComponentPeer.c
- test/jdk/TEST.groups
- test/jdk/jb/javax/swing/Popup/WLPopupAsParent.java
[JBR-7016](https://youtrack.jetbrains.com/issue/JBR-7016) IDEA 2024.2 Wayland: UI Crash when selecting Code and pressing Alt+Enter
Account for the possibility of popups having another popup as their parent.
> JBR-7016 IDEA 2024.2 Wayland: UI Crash when selecting Code and pressing Alt+Enter

- src/java.desktop/unix/classes/sun/awt/X11GraphicsDevice.java
[JBR-7483](https://youtrack.jetbrains.com/issue/JBR-7483) Monitor resolution is incorrect in jbr 21
Re-set screen bounds after scale has been changed
> JBR-7483 Monitor resolution is incorrect in jbr 21
